crates/rpc/src/lib.rs
prefer the rpc be served over the root path `/` instead of `/rpc`
=> fix: serve rpc over the root instead of /rpc

crates/rpc/src/config.rs, crates/rpc/src/lib.rs, crates/rpc/src/util.rs
- impls `crate::serve_ws` to serve the router over both HTTP and WS
- ports `RpcServerGuard` from node
- adds `ServeConfig` 
- `impl From<reth::RpcServerArgs> for ServeConfig`
cc @rswanson are the routes `/` and `/ws` reasonable? edit: @Evalir pointed out it's traditional in eth to use a different port
=> feat: serve router over ws

crates/rpc/src/signet/endpoints.rs, crates/rpc/src/signet/mod.rs, crates/rpc/src/util.rs
Adds `signet_callBundle` to the rpc server, which will simulate the bundle and return a response
=> Add `signet_callBundle` to the RPC

Cargo.toml, crates/bundle/src/call/driver.rs, crates/bundle/src/call/ty.rs, crates/bundle/src/send.rs, crates/evm/src/aliases.rs, crates/evm/src/driver.rs, crates/evm/src/lib.rs, crates/evm/src/orders/inspector.rs, crates/evm/src/orders/mod.rs, crates/extract/src/block.rs, crates/types/src/magic_sig.rs, crates/zenith/src/bindings.rs, crates/zenith/src/block.rs
- Restore DB to driver traits to handle revm@20
- Migrate to `Layered`
- Add `SignetInspector` trait
- move generics to new trevm order
=> dep: upgrade to trevm 0.20.7

crates/rpc/src/ctx.rs, crates/rpc/src/eth/endpoints.rs, crates/rpc/src/lib.rs, crates/rpc/src/receipts.rs, crates/types/src/magic_sig.rs, tests/artifacts/enter_tx.json
fix(rpc): use `SignetReceiptBuilder` to build receipts
in-houses the `build_receipt` fn, to add support for transactions that use `MagicSig`s (they're not directly signed by the sender, which is the case for signet events). Usage of this type fixes both `eth_getTransactionReceipt` and `eth_getBlockReceipts`.
Closes ENG-970.
=> fix(rpc): introduce in-house `build_signet_receipt` to build receipts

crates/types/Cargo.toml, crates/types/src/signing/fill.rs, crates/types/src/signing/order.rs
transform a `SignedOrder` or `Fill` into the `TransactionRequests` necessary to `initiate` or `fill` them, respectively.
=> feat: SignedOrder/Fill to_tx helpers

crates/rpc/examples/filler.rs, crates/types/src/agg/order.rs
Example code for Fillers of Signet Orders.
=> feat: example code for Fillers

clippy.toml, crates/rpc/src/interest/subs.rs
Closes ENG-1086
We'll ignore a large error warning by just bumping the size. it's barely above the threshold and non-consequential.
For the large enum variant lint, we now box logs/headers when outputting them from the subscription buffer.
=> fix(ci): handle new clippy lints

crates/constants/Cargo.toml, crates/constants/src/chains/pecorino.rs, crates/constants/src/chains/test_utils.rs, crates/constants/src/lib.rs, crates/constants/src/types/environment.rs, crates/constants/src/types/mod.rs, crates/evm/src/lib.rs, crates/extract/src/extractor.rs, crates/rpc/examples/filler.rs, crates/rpc/examples/order.rs, crates/sim/tests/basic_sim.rs, crates/tx-cache/Cargo.toml, crates/tx-cache/src/client.rs
- add `SignetEnvironmentConstants` and `SignetConstants` (system + environment)
- contains names for Host and Rollup networks & the Transaction Cache URL
- adds `TxCache::pecorino()` and `TxCache::pecorino_with_client(client: Client)`
- updates Filler and Order example code to use new constants
=> feat: add chain names & tx cache URL

crates/constants/src/lib.rs, crates/constants/src/types/chains.rs, crates/constants/src/types/environment.rs, crates/constants/src/types/host.rs, crates/constants/src/types/mod.rs, crates/constants/src/types/rollup.rs, crates/extract/src/test_utils/host_spec.rs, crates/extract/src/test_utils/ru_spec.rs
in service of implementing `FromEnvVar` in [bin-base](https://github.com/init4tech/bin-base/) using `impl_for_parseable!` [macro](https://github.com/init4tech/bin-base/blob/7a693c002273142da3fa1727222d19ffb55258f7/src/utils/from_env.rs#L584C14-L584C32)
Implemented for all types with `pecorino()`/`test()` instantiations, _except_ purposefully did not implement for `TxCache` because I thought we may want the behavior for that to be different - e.g. treat the env var as the tx cache endpoint.
=> feat: impl FromStr for chain constants

crates/evm/src/driver.rs, crates/evm/src/journal/coder.rs, crates/evm/src/lib.rs, crates/evm/src/orders/inspector.rs, crates/evm/src/orders/mod.rs, crates/rpc/src/ctx.rs, crates/rpc/src/lib.rs
Cleans up some imports by moving them out of reth. Thinking long-term we'd like to remove reth as a dep here
=> chore: trim some reth imports

Cargo.toml, crates/bundle/src/call/driver.rs, crates/bundle/src/call/ty.rs, crates/bundle/src/send/bundle.rs, crates/evm/src/convert.rs, crates/evm/src/driver.rs, crates/evm/src/orders/inspector.rs, crates/extract/src/events.rs, crates/extract/src/extracted.rs, crates/extract/src/test_utils/host_spec.rs, crates/rpc/src/ctx.rs, crates/rpc/src/interest/kind.rs, crates/rpc/src/receipts.rs, crates/types/src/magic_sig.rs, crates/types/src/seq/mod.rs, crates/types/src/seq/resp.rs, crates/zenith/src/block.rs, crates/zenith/src/lib.rs
=> feat(repo): migrate to latest reth/alloy/trevm

crates/sim/src/built.rs, crates/sim/src/env.rs, crates/sim/src/task.rs
This PR adds a block number field and a setter for tracking the block number of a given built block.
=> feat: add block number property to BuiltBlock

Cargo.toml, crates/tx-cache/src/client.rs
Only checks for success. Useful for any API handlers that do not return any data, like the Orders PUT handler
=> chore(tx-cache): add method to forward without decoding response bodies

Cargo.toml, crates/evm/src/outcome.rs, crates/evm/src/result.rs, crates/test-utils/src/chain.rs, crates/test-utils/src/convert.rs, crates/test-utils/src/specs/host_spec.rs
feat: add methods to execution outcome
chore: version
=> feat: add methods to execution outcome

Cargo.toml, crates/bundle/src/send/bundle.rs, crates/rpc/examples/filler.rs, crates/rpc/src/eth/endpoints.rs
- log transaction request *before* editing gas
- log after editing gas
- log estimation result from trevm
=> improve logging on estimate_gas

Cargo.toml, crates/constants/Cargo.toml, crates/constants/src/lib.rs, crates/sim/src/item.rs
chore: pin alloy-trie
chore: pin bad alloy versions
chore: silence clippy
=> chore: pin bad alloy versions

crates/sim/src/cache.rs, crates/sim/src/env.rs, crates/sim/src/outcome.rs
The SimItems cache key was variably names as `score`, `identifier`, and `key`. However, `score` and `identifier` are both also used elsewhere in this code to refer to different values. I found this to make the code less readable.
This PR
- Differentiates between `cache_rank` (the item's ordering within the cache) and `score` (final, actual simulation score based on beneficiary balance change) 
- Differentiates between `cache_rank` and `identifier` (tx hash for txns, UUID for bundles)
Also updates logging to use SimItem `identifier` (rather than `cache_rank`) to make the logs more readable & searchable.
=> clarify between `cache_rank` and `identifier`

crates/sim/src/cache.rs
`add_bundle` is no longer fallible, as we simply skip over invalid bundles. Therefore, we don't need to return `Result`.
=> chore(sim): remove unnecessary `Result` for `add_bundle`

crates/sim/src/task.rs
fix(sim): Make simulation process actually continuous
Right now, the simulator stops as soon as there are no more items to simulate. This actually is not correct behavior, as we could be early in the slot, with more items coming in later in the slot which could yield a higher total payout on the block.
What we actually want, is to simply skip doing the round at all if there are no items, sleep for a certain amount of time (bounded by the deadline), and either break (if we slept until the deadline) or continue if there's still time remaining.
The resulting behavior is that the simulator always runs until the deadline, ensuring that items that come later in the slot, up until the deadline, can be simulated and included in the block.
chore: properly break if we sleep until deadline
=> fix(sim): Make simulation process actually continuous

Cargo.toml, crates/test-utils/src/chain.rs
Right now, this timestamp isn't divisible by 12. After fixing the bug we had on blob extraction on the node (https://github.com/init4tech/signet-node/pull/557/files#diff-c630b8329efc76498eaf78bdf3073dcdaefaacb9325e5731b7d1d8cae855d791R262), we now don't conform to an invariant that the calculator has when using `slot_ending_at`: The timestamp must be a slot boundary. We know if it's a slot boundary if it's divisible by 12 in the context of the start timestamp. For tests, this is 0, so any timestamp divisible by 12 will do.
=> chore(tests): Make timestamp divisible by 12 to conform to slot invariant

crates/rpc/examples/filler.rs, crates/types/src/agg/order.rs, crates/types/src/signing/error.rs, crates/types/src/signing/fill.rs
Within Fills, the Output chain ID is intended to indicate the _origin_ chain ID, NOT the destination chain ID. 
Confusion arose because the Solidity was designed to "overload" the `chainId` field on the Output struct depending on the context; in the context of Orders, it should specify the **destination** chain ID; in the context of Fills, it should specify the **origin** chain ID.
Previously, the SDK Fill signing logic incorrectly populated Outputs with the destination chain ID.
Fill Outputs must specify the origin chain ID.
This PR updates the Fill signing logic in the `UnsignedFill` struct to explicitly add the origin chain ID before signing. 
If, at some point in the future, `AggregateOrders` was used to agg Orders from different origin chains, this logic could become problematic. It …
=> fix: credit origin chain ID on SignedFills

Cargo.toml
Bump version from 0.6.0 to 0.7.0 across all workspace packages.
- Updated the workspace package version from 0.6.0 to 0.7.0 in the root Cargo.toml
- Updated all internal dependency versions from 0.6.0 to 0.7.0 for all signet crates:
- signet-bundle
- signet-constants
- signet-evm
- signet-extract
- signet-node
- signet-rpc
- signet-sim
- signet-types
- signet-tx-cache
- signet-zenith
- Verify that the project builds successfully with `cargo build`
- Run tests to ensure all dependencies resolve correctly with `cargo test`
- Check that any downstream projects depending on these crates can update to the new version
This version bump prepares for a new release with significant changes that warrant a minor version increment according to semantic versioning principles.
=> chore(deps): bump version

Cargo.toml
This release marks the first with Signet SDK  having USD as the native asset.
=> chore: v0.8.0

Cargo.toml, crates/zenith/src/bindings.rs
Add missing `Clone` impls to Call enums
these can't be derived due to alloy structuring of sol macro :(
=> feat: add clone impls for binding calls

Cargo.toml, crates/constants/src/chains/pecorino.rs
New host chain requires new constants
=> fix: new constants for pecorino

Cargo.toml, crates/test-utils/src/specs/mod.rs, crates/test-utils/src/specs/notif_spec.rs
Fix: make the type usable and not unnameable
=> fix: export exexnotification

crates/bundle/src/send/driver.rs, crates/sim/src/env.rs, crates/types/src/agg/fill.rs
Adds Order enforcement to the bundle execution driver :)
A limitation of this is that it doesn't allow bundles that internally underfill (i.e. implicit dependencies on prior overfills)
=> fix: SignetEthBundleDriver now enforces market rules internally

crates/test-utils/tests/basic_sim.rs
the test flakes due to concurrency and stuff. make it not
=> fix: make test not flake

Cargo.toml, crates/bundle/src/lib.rs, crates/constants/src/lib.rs, crates/evm/src/lib.rs, crates/extract/src/lib.rs, crates/journal/src/lib.rs, crates/sim/src/lib.rs, crates/tx-cache/src/lib.rs, crates/types/src/lib.rs, crates/zenith/src/lib.rs
As per recommendation, see https://users.rust-lang.org/t/fallout-from-removal-of-doc-auto-cfg/134435
=> fix(docs): Remove `auto_doc_cfg` usage
